/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#c3c0ff',
        'surface-bright': '#fbf8ff',
        'on-secondary-container': '#fffbff',
        'on-tertiary-container': '#ffa583',
        'outline-variant': '#c4c5d5',
        'inverse-surface': '#2f3037',
        'tertiary-fixed-dim': '#ffb59a',
        'outline': '#757684',
        'surface-container-highest': '#e3e1eb',
        'surface-dim': '#dad9e3',
        'on-primary-fixed': '#001453',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#100069',
        'on-background': '#1a1b22',
        'surface-container-high': '#e8e7f1',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#ffdbce',
        'background': '#fbf8ff',
        'secondary': '#4e45d5',
        'on-primary-fixed-variant': '#173bab',
        'error': '#ba1a1a',
        'tertiary-container': '#872d00',
        'surface-tint': '#3755c3',
        'secondary-container': '#6860ef',
        'primary-fixed-dim': '#b8c4ff',
        'surface-container-low': '#f4f2fc',
        'surface': '#fbf8ff',
        'primary-fixed': '#dde1ff',
        'surface-variant': '#e3e1eb',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#802a00',
        'on-surface-variant': '#444653',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#380d00',
        'inverse-on-surface': '#f1f0fa',
        'on-error-container': '#93000a',
        'secondary-fixed': '#e3dfff',
        'primary-container': '#1e40af',
        'tertiary': '#611e00',
        'inverse-primary': '#b8c4ff',
        'on-primary': '#ffffff',
        'primary': '#00288e',
        'on-primary-container': '#a8b8ff',
        'surface-container': '#eeedf7',
        'on-surface': '#1a1b22',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#372abf',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-width': '260px',
        unit: '4px',
        gutter: '20px',
        xl: '32px',
        md: '16px',
        lg: '24px',
        sm: '8px',
        xs: '4px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-stat': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'display-stat': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
};
